In [1]:
import numpy as np
import pandas as pd


# converting csv file to dataframe
file = pd.read_csv('/Users/jeffreybiondi/Desktop/Jeffums Portfolio/moviesPythonData.csv', index_col = 0)

file

,show_id,type,title,director,cast,country,rating,release_year,year_added,duration_min,number_of_seasons,listed_in,description
0,s1,TV Show,3%,NaN,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,TV-MA,2020,2020,NaN,4.0,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...
1,s2,Movie,7:19,Jorge Michel Grau,"Demián Bichir, Héctor Bonilla, Oscar Serrano, ...",Mexico,TV-MA,2016,2016,93.0,NaN,"Dramas, International Movies",After a devastating earthquake hits Mexico Cit...
2,s3,Movie,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",Singapore,R,2011,2018,78.0,NaN,"Horror Movies, International Movies","When an army recruit is found dead, his fellow..."
3,s4,Movie,9,Shane Acker,"Elijah Wood, John C. Reilly, Jennifer Connelly...",United States,PG-13,2009,2017,80.0,NaN,"Action & Adventure, Independent Movies, Sci-Fi...","In a postapocalyptic world, rag-doll robots hi..."
4,s5,Movie,21,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",United States,PG-13,2008,2020,123.0,NaN,Dramas,A brilliant group of students become card-coun...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7782,s7783,Movie,Zozo,Josef Fares,"Imad Creidi, Antoinette Turk, Elias Gergi, Car...","Sweden, Czech Republic, United Kingdom, Denmar...",TV-MA,2005,2020,99.0,NaN,"Dramas, International Movies",When Lebanon's Civil War deprives Zozo of his ...
7783,s7784,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,TV-14,2015,2019,111.0,NaN,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...
7784,s7785,Movie,Zulu Man in Japan,NaN,Nasty C,NaN,TV-MA,2019,2020,44.0,NaN,"Documentaries, International Movies, Music & M...","In this documentary, South African rapper Nast..."
7785,s7786,TV Show,Zumbo's Just Desserts,NaN,"Adriano Zumbo, Rachel Khoo",Australia,TV-PG,2019,2020,NaN,1.0,"International TV Shows, Reality TV",Dessert wizard Adriano Zumbo looks for the nex...
7786,s7787,Movie,ZZ TOP: THAT LITTLE OL' BAND FROM TEXAS,Sam Dunn,NaN,"United Kingdom, Canada, United States",TV-MA,2019,2020,90.0,NaN,"Documentaries, Music & Musicals",This documentary delves into the mystique behi...

In [2]:
# Exploring United States in the Data

titleCount = file['title'].str.contains('United States').sum()

print ('There are ' + str(titleCount) + ' movies that mention United States in the title.')

descCount = file['description'].str.contains('United States').sum()

print('There are ' + str(descCount) + ' movies that mention United States in the description.')

countryCount = file['country'].str.contains('United States').sum()

print('There are ' + str(countryCount) + ' movies that are from the United States.')

There are 2 movies that mention United States in the title.
There are 5 movies that mention United States in the description.
There are 3291 movies that are from the United States.

In [3]:
# A Funtion That Will Search for a Director

def searchDirectors(directorName):
    myDirectors = file['director'].str.upper()
    # this makes all values in director key column UPPER
    # print(type(myDirectors))
    directorCount =  myDirectors.str.contains(directorName.upper()).sum()
    # counts the number of rows containing directorName
    if directorCount > 0:
      print('There are', directorCount, 'directors named', directorName, 'in this dataset.')
    else:
      print('No directors were found with the name:', directorName)

searchDirectors("pAuL")
# Using the fuction to search for input()

There are 67 directors named pAuL in this dataset.

In [4]:
# Finding the Most Common Words in the Longest Duration Movies

from collections import Counter

movieDurations = file[['title','duration_min','description']].dropna()
# print(movieDurations)
# movies' durations and description (no sort, remove NaN)

durationMax = movieDurations.max()
print('The longest movie in minutes is:',durationMax["duration_min"])

top10 = movieDurations.sort_values(by = 'duration_min', ascending = False).head(10)
print(top10)
# top 10 movies sorted by largest duration

print('\n')

print('The 20 most common words in the description for the top 10 longest movies:')
words = Counter(" ".join(top10['description']).lower().split()).most_common(20)
print(words)
# splits description and counts the number of most common words (lowercase)

The longest movie in minutes is: 253.0
                             title  duration_min  \
6850        The School of Mischief         253.0
4490                No Longer kids         237.0
3694            Lock Your Girls In         233.0
5108               Raya and Sakina         230.0
5376                        Sangam         228.0
3521                        Lagaan         224.0
3195                  Jodhaa Akbar         214.0
6507                  The Irishman         209.0
3282      Kabhi Khushi Kabhie Gham         209.0
4484  No Direction Home: Bob Dylan         208.0

                                            description
6850  A high school teacher volunteers to transform ...
4490  Hoping to prevent their father from skipping t...
3694  A widower believes he must marry off his three...
5108  When robberies and murders targeting women swe...
5376  Returning home from war after being assumed de...
3521  In 1890s India, an arrogant British commander ...
3195  In 16th-century India, what begins as a strate...
6507  Hit man Frank Sheeran looks back at the secret...
3282  Years after his father disowns his adopted bro...
4484  Featuring rare concert footage and interviews ...


The 20 most common words in the description for the top 10 longest movies:
[('a', 13), ('to', 8), ('his', 8), ('and', 5), ('the', 5), ('he', 4), ('of', 4), ('from', 3), ('for', 3), ('in', 3), ('has', 2), ('father', 2), ('with', 2), ('marry', 2), ('marrying', 2), ('love.', 2), ('on', 2), ('true', 2), ('after', 2), ('woman', 2)]